# Use the official image as a parent image.
FROM alpine 

# Installing necessary software
# temproray error comes from here!
RUN apk add --update --no-cache influxdb telegraf

# Copying configuration files
RUN rm /etc/telegraf.conf
COPY ./telegraf.conf /etc/telegraf/

# Copy & run srcs/start.sh
COPY start.sh /
RUN chmod +x /start.sh
CMD ["/start.sh"]

# Opening ports
EXPOSE 8086 
