# Use the official image as a parent image.
FROM alpine 

# Installing necessary software
RUN apk add --update --no-cache mysql mysql-client telegraf

# Copying configuration files
RUN rm /etc/telegraf.conf
COPY ./telegraf.conf /etc/telegraf/
COPY my.cnf /etc/mysql/

# Copy & run srcs/start.sh
COPY start.sh /
RUN chmod +x /start.sh
ENTRYPOINT ["/start.sh"]

# Opening ports
EXPOSE 80 443
