# Use the official image as a parent image.
FROM alpine 

# Installing necessary software
RUN apk add --update --no-cache grafana telegraf

# Copying configuration files
RUN rm /etc/telegraf.conf
COPY ./telegraf.conf /etc/telegraf/
COPY grafana.db /usr/share/grafana/data/

# Copy & run srcs/start.sh
COPY start.sh /
RUN chmod +x /start.sh
CMD ["/start.sh"]

# Opening ports
EXPOSE 3000 
