# Use the official image as a parent image.
FROM alpine 

# Set the working directory.
WORKDIR /www

# Installing necessary software
RUN apk update \
	&& apk add nginx openssl 

RUN adduser -D -g 'www' www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

# Copying configuration files
COPY nginx.conf /etc/nginx/
COPY index.html /www/

# Copy & run srcs/start.sh
COPY start.sh /
RUN chmod +x /start.sh
ENTRYPOINT ["/start.sh"]

# Opening ports
EXPOSE 80 443
