# Use the official image as a parent image.
FROM alpine 

# Set the working directory.
WORKDIR /www

# Installing necessary software
RUN apk add --update --no-cache nginx openssl telegraf

RUN adduser -D -g 'www' www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

# Copying configuration files
RUN rm /etc/telegraf.conf
COPY ./telegraf.conf /etc/telegraf/
COPY nginx.conf /etc/nginx/
COPY index.html /www/

# Copy & run srcs/start.sh
COPY start.sh /
RUN chmod +x /start.sh
ENTRYPOINT ["/start.sh"]

# Opening ports
EXPOSE 80 443
