# Use the official image as a parent image.
FROM alpine 

# Set the working directory.
WORKDIR /www

# Installing necessary software
RUN apk add --update --no-cache wget telegraf nginx openssl php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl php7-mbstring php7-json php7-session

RUN adduser -D -g 'www' www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

# Conf phpMyAdmin
RUN wget https://files.phpmyadmin.net/phpMyAdmin/4.9.5/phpMyAdmin-4.9.5-all-languages.tar.gz 
RUN tar xzf phpMyAdmin-4.9.5-all-languages.tar.gz
RUN mv phpMyAdmin-4.9.5-all-languages/ phpmyadmin/
RUN rm phpmyadmin/config.sample.inc.php
RUN rm -rf phpMyAdmin-4.9.5-all-languages.tar.gz

# Copying configuration files
RUN rm /etc/telegraf.conf
COPY ./telegraf.conf /etc/telegraf/
COPY nginx.conf /etc/nginx/
COPY config.inc.php /www/phpmyadmin/ 

# Copy & run srcs/start.sh
COPY start.sh /
RUN chmod +x /start.sh
ENTRYPOINT ["/start.sh"]

# Opening ports
EXPOSE 80 443
