# Use the official image as a parent image.
FROM alpine 

# Set the working directory.
WORKDIR /www

# Installing necessary software
RUN apk update \
	&& apk add wget nginx openssh openssl php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl php7-mbstring php7-json php7-session

RUN adduser -D -g 'www' www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

# Copying configuration files
COPY nginx.conf /etc/nginx/
COPY wp-config.php /www/wordpress/ 

# Copy & run srcs/start.sh
COPY start.sh /
RUN chmod +x /start.sh
ENTRYPOINT ["/start.sh"]

# Opening ports
EXPOSE 80 443 22
