# Use the official image as a parent image.
FROM alpine 

# Installing necessary software
RUN apk update \
	&& apk add vsftpd openssl build-base linux-pam-dev curl db-utils\
	&& mkdir /pam \
	&& cd pam \
	&& curl -sSL https://github.com/tiwe-de/libpam-pwdfile/archive/v1.0.tar.gz | tar xz --strip 1 \
	# Dont forget to rm /pam
	&& make install \ 
	&& rm -rf /pam \
	&& mkdir -p /home/vsftpd \
	&& chown -R ftp:ftp /home/vsftpd

# Copying configuration files
COPY vsftpd.conf /etc/vsftpd/
COPY vsftpd_virtual /etc/pam.d/

# Copy & run srcs/start.sh
COPY start.sh /
RUN chmod +x /start.sh
CMD ["/start.sh"]

# Opening ports
EXPOSE 20 21 21100-21110
